version: '3.3'

services: # padrão compose
  db: # Container de MySQL - nome qualquer
    image: mysql:5.7 # FROM mysql:5.7
    ports:
      - "4555:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always #garantia de atualizão do meu projeto no container
    env_file:
      - ./config/db.env

  wordpress:
    depends_on: #dependencias desse container
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wordpess.env
volumes:
  db_data: {}